name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'main/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            set -e

            cd /root/MadCamp/Madmon

            git fetch origin
            git reset --hard origin/main

            chmod +x scripts/backend.sh

            ./scripts/backend.sh